name: Deploy to VPS
on:
  push:
    branches: [ruvds]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update code
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          timeout: 5m
          script: |
            cd /var/www/odet-nadezhdu
            git pull origin ruvds
            npm ci --prefer-offline --no-audit
      
      - name: Build application
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          timeout: 15m
          command_timeout: 15m
          script: |
            cd /var/www/odet-nadezhdu
            NODE_OPTIONS="--max-old-space-size=4096" npm run build
      
      - name: Restart application
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          timeout: 2m
          script: |
            cd /var/www/odet-nadezhdu
            pm2 restart odet-nadezhdu